[package]
name = "near-btp"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[workspace]
members = [
    "bmc",
    "bmv",
    "bsh/bsh-generic",
    "bsh/token-bsh",
    "libraries",
]
[features]
integration-tests = []

[dev-dependencies]
bmc = { path = "./bmc" }
bsh-generic = { path = "./bsh/bsh-generic" }
libraries = { path = "./libraries" }
token-bsh = { path = "./bsh/token-bsh" }
near-sdk = "3.1.0"
near-sdk-sim = "3.2.0"
lazy_static = "1.4.0"
kitten = "^0.1.3"

[dev-dependencies.near-chain-configs]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-logger-utils]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-primitives]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.testlib]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-network]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-telemetry]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.actix]
version = '=0.11.0-beta.2'

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
# Tell `rustc` to optimize for small code size.
opt-level = "z"
debug = false
panic = "abort"