[package]
name = "near-btp"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"
rust = "1.51"

[workspace]
members = [
    "bsh-generic"
]

[dev-dependencies]
bmc = { path = "./bmc" }
near-sdk = "2.0.0"
lazy_static = "1.4.0"

[dev-dependencies.near-chain-configs]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-logger-utils]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-primitives]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.testlib]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-network]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.near-telemetry]
default-features = false
git = 'https://github.com/HugoByte/nearcore.git'
tag = '1.19.1'
version = '0.1.0'

[dev-dependencies.actix]
version = '=0.11.0-beta.2'

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
