[package]
name = "libraries"
version = "0.1.0"
description = "Data Types for BSH, BMC, and BMV Contracts"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[dependencies]
btp-common = { path="../../btp-common" }
merkle-tree-accumulator = "0.1.3"
near-sdk = "3.1.0"
