version: "3.9"  # optional since v1.27.0
services:
  goloop:
    build:
      context: .
      args:
        ICONBRIDGE_VERSION: latest
        GOLOOP_IMAGE: goloop:latest
    ports:
      - "9080:9080"
    volumes:
      - config:/goloop/config
      - data:/goloop/data
    environment:
      - GOLOOP_NODE_DIR=/goloop/data/goloop
      - GOLOOP_LOG_WRITER_FILENAME=/goloop/data/log/goloop.log
  iconbridge_src:
    image: iconbridge:latest
    volumes:
      - config:/iconbridge/config
      - data:/iconbridge/data
    environment:
      - ICONBRIDGE_BASE_DIR=/iconbridge/data/iconbridge_src
      - ICONBRIDGE_CONFIG=/iconbridge/config/src.config.json
      - ICONBRIDGE_SRC_ADDRESS=/iconbridge/config/btp.src
      - ICONBRIDGE_SRC_ENDPOINT=http://goloop:9080/api/v3/src
      - ICONBRIDGE_DST_ADDRESS=/iconbridge/config/btp.dst
      - ICONBRIDGE_DST_ENDPOINT=http://goloop:9080/api/v3/dst
      - ICONBRIDGE_OFFSET=/iconbridge/config/offset.src
      - ICONBRIDGE_KEY_STORE=/iconbridge/config/src.ks.json
      - ICONBRIDGE_KEY_SECRET=/iconbridge/config/src.secret
      - ICONBRIDGE_LOG_WRITER_FILENAME=/iconbridge/data/log/iconbridge_src.log
    links:
      - goloop
  iconbridge_dst:
    image: iconbridge:latest
    volumes:
      - config:/iconbridge/config
      - data:/iconbridge/data
    environment:
      - ICONBRIDGE_BASE_DIR=/iconbridge/data/iconbridge_dst
      - ICONBRIDGE_CONFIG=/iconbridge/config/dst.config.json
      - ICONBRIDGE_SRC_ADDRESS=/iconbridge/config/btp.dst
      - ICONBRIDGE_SRC_ENDPOINT=http://goloop:9080/api/v3/dst
      - ICONBRIDGE_DST_ADDRESS=/iconbridge/config/btp.src
      - ICONBRIDGE_DST_ENDPOINT=http://goloop:9080/api/v3/src
      - ICONBRIDGE_OFFSET=/iconbridge/config/offset.dst
      - ICONBRIDGE_KEY_STORE=/iconbridge/config/dst.ks.json
      - ICONBRIDGE_KEY_SECRET=/iconbridge/config/dst.secret
      - ICONBRIDGE_LOG_WRITER_FILENAME=/iconbridge/data/log/iconbridge_dst.log
    links:
      - goloop
volumes:
  config: {}
  data: {}