[package]
name = "bsh-generic"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[dependencies]
bincode = "1.3.3"
log = "0.4.14"
near-sdk = "3.1.0"
btp-common = {path="../../btp-common"}
#lazy_static = "1.4.0"