[package]
name = "bmv"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
btp-common = { path = "../../btp-common" }
libraries = { path = "../libraries" }
near-sdk = "3.1.0"
rlp = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
vrf = "0.2.2"