name: Build BSC Node
on:
  push:
    branches:
      - repo_mgmt_and_github_actions
      - repo_mgmt_cicd
    paths:
      - 'provision/bsc'
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build bsc image
        working-directory: ./provision/bsc/bmr/build
        run: |
             ./build.sh
