name: Build hmny

on:
  push:
    branches: [ repo_mgmt_cicd ]
    # paths:
    #   - 'cmd'
  pull_request:
    branches: [ repo_mgmt_cicd ]
    # paths:
    #   - 'cmd'

jobs:
  build-bmr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        working-directory: ./provision/hmny/bmr/build
        env:
          DOCKER_TAG: ${SHORT_SHA}
          DOCKER_REPO: ${DOCKER_USER}
          DOCKER_IMG: "bmr-hmny"
        run: |
             ./build.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ACCESS_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push image
        run: |
             docker tag localhost:5000/bmr ${DOCKER_REPO}:bmr-hmny-${SHORT_SHA}
             docker push ${DOCKER_REPO}:bmr-hmny-${SHORT_SHA}

  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        working-directory: ./provision/hmny/chain/build
        run: |
             ./build.sh
