name: Deploy icon contracts
on:
  # push:
  #   paths:
  #     - 'provision/icon/contracts'
  push:
    branches: [ repo_mgmt_and_github_actions ]
  workflow_call:
  paths:
    - 'provision/icon/contracts'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ACCESS_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy
        working-directory: ./provision/icon/contracts/deploy
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        run: |
             ./deploy.sh
