name: 'Deploy Solidity BMC to BSC Testnet'

on:
  push:
    branches:
      - feat/344-deploy-solidity-bmc-bsc
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-bmc-solidity:
    name: deploy solidity BMC to BSC Testnet
    runs-on: ubuntu-latest
    container:
      image: iconbridge/build
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: npm install
        working-directory: ./solidity/bmc
        run: npm install

      - name: Truffle compile and Deploy solidity bmc
        working-directory: ./solidity/bmc
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.BSC_PRIVATE_KEY }}
          BSC_RPC_URI: ${{ secrets.BSC_RPC_URI }}
          BSC_NID: ${{ secrets.BSC_NID }}
          BSC_BMC_NET: ${{ secrets.BSC_BMC_NET }}
        run: |
          truffle compile --all
          PRIVATE_KEY=$PRIVATE_KEY BSC_RPC_URI=$BSC_RPC_URI BSC_NID=$BSC_NID BSC_BMC_NET=$BSC_BMC_NET BSC_NID=97 \
          truffle migrate --network bsc --compile-none

      # - name: Deployment txresult
      #   working-directory: ./javascore
      #   shell: bash
      #   timeout-minutes: 1
      #   env:
      #     GOLOOP_RPC_URI: ${{ secrets.GOLOOP_RPC_URI }}
      #   run: |
      #     while true; do
      #       str=`goloop rpc --uri $GOLOOP_RPC_URI txresult $(cat tx.icon.bmc) | tee tx-icon-bmc || exit 0`
      #       echo Output: $str
      #       if [[ $str =~ logsBloom ]]; then
      #         break
      #       fi
      #       echo Wait
      #       sleep 2
      #     done
      #     echo Finished

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Sync tx.icon.bmc
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #   run: |
      #     aws s3 cp ./javascore/tx-icon-bmc s3://$AWS_S3_BUCKET/tx-icon-bmc-$GITHUB_REF_NAME
      #     aws s3 mv ./javascore/tx-icon-bmc s3://$AWS_S3_BUCKET/tx-icon-bmc
