name: Deploy hmny contracts
on:
  push:
    branches:
      - repo_mgmt_and_github_actions
      - repo_mgmt_cicd
    paths:
      - 'provision/hmny/contracts'
  pull_request:
    branches:
      - repo_mgmt_and_github_actions
      - repo_mgmt_cicd
  workflow_call:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_ACCESS_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy
        working-directory: ./provision/hmny/contracts/deploy
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
        run: |
             ./deploy.sh
