name: HMNY Build

on:
  push:
    branches: [ repo_mgmt_and_github_actions ]
    # paths:
    #   - 'cmd'
  pull_request:
    branches: [ repo_mgmt_and_github_actions ]
    # paths:
    #   - 'cmd'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        working-directory: ./provision/hmny/build
        run: |
             ./build.sh
