[package]
name = "token-service"
version = "0.1.0"
authors = ["Icon Foundation<foo@icon.foundation>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
btp-common = { path = "../../../btp-common" }
libraries = { path = "../../libraries" }
near-sdk = { git = "https://github.com/near/near-sdk-rs.git" }

[[test]]
name = "test_ownership_management"
path = "tests/test_ownership_management.rs"
